import 'dart:io';
import 'package:code_builder/code_builder.dart' as cb;
import 'package:dart_style/dart_style.dart';
import 'package:path/path.dart' as p;

import 'naming_utils.dart';
import 'package:zuraffa_graphql/zuraffa_graphql.dart';

/// Generates `documents.dart` — a file with parsed `DocumentNode` constants
/// for every `.graphql` file in a directory.
///
/// ```dart
/// // data/datasources/product/graphql/documents.dart
/// // GENERATED — DO NOT EDIT BY HAND
/// final getProductDocument = gql(r'''...''');
/// final addItemToOrderDocument = gql(r'''...''');
/// ```
///
/// This file is **regenerated** on every `zfa build` and **never edited by hand**.
class DocumentsDartGenerator {
  DocumentsDartGenerator();
  static final _formatter = DartFormatter(
    languageVersion: DartFormatter.latestLanguageVersion,
  );

  /// Scan [graphqlDir] for `.graphql` files and generate `documents.dart`.
  String generate({required String graphqlDir, required String outputPath}) {
    final dir = Directory(graphqlDir);
    if (!dir.existsSync()) {
      throw StateError('GraphQL directory does not exist: $graphqlDir');
    }

    // Collect all .graphql files first
    final graphqlFiles = <File>[];
    for (final entity in dir.listSync(recursive: true)) {
      if (entity is! File) continue;
      if (!entity.path.endsWith('.graphql')) continue;
      graphqlFiles.add(entity);
    }

    // Sort by path for deterministic output
    graphqlFiles.sort((a, b) => a.path.compareTo(b.path));

    final documentVars = <cb.Field>[];
    final seenVarNames = <String>{};

    for (final file in graphqlFiles) {
      final fileName = p.basenameWithoutExtension(file.path);
      final varName = '${NamingUtils.documentVarName(fileName)}Document';
      final content = file.readAsStringSync();

      // Check for duplicate variable names (from different directories)
      if (seenVarNames.contains(varName)) {
        throw StateError(
          'Duplicate document variable name "$varName" detected. '
          'Files from different directories produced the same camelCase name. '
          'Please rename one of the .graphql files to avoid collision.\n'
          'Current file: ${file.path}',
        );
      }
      seenVarNames.add(varName);

      // Skip unvalidated files (they have a header comment)
      final cleanContent = content
          .split('\n')
          .where((line) => !line.startsWith('#'))
          .join('\n')
          .trim();

      documentVars.add(
        cb.Field((f) {
          f
            ..name = varName
            ..modifier = cb.FieldModifier.final$
            ..type = cb.refer('DocumentNode')
            ..assignment = cb.refer('gql').call([
              cb.literalString(cleanContent, raw: true),
            ]).code;
        }),
      );
    }

    final library = cb.Library((b) {
      b.directives.add(
        cb.Directive.import('package:gql/ast.dart', show: ['DocumentNode']),
      );
      b.directives.add(
        cb.Directive.import('package:gql/language.dart', show: ['gql']),
      );

      b.body.add(
        cb.Code(
          '// GENERATED CODE — DO NOT EDIT BY HAND\n'
          '// Generated by zfa gql plugin from .graphql files in ${p.basename(graphqlDir)}/\n'
          '// Regenerated on every `zfa build`\n',
        ),
      );

      for (final field in documentVars) {
        b.body.add(field);
      }
    });

    final emitter = cb.DartEmitter();
    final raw = library.accept(emitter).toString();
    return _formatter.format(raw);
  }

  /// Generate and write the file.
  void generateAndWrite({
    required String graphqlDir,
    required String outputPath,
  }) {
    final code = generate(graphqlDir: graphqlDir, outputPath: outputPath);
    final file = File(outputPath);
    file.createSync(recursive: true);
    file.writeAsStringSync(code);
  }
}
